package com.btc.trade.entity;

// Generated 2013-4-2 23:48:44 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Trade generated by hbm2java
 */
@Entity
@Table(name = "trade", catalog = "test")
public class Trade implements java.io.Serializable {

	private Integer tradeid;
	private String seller;
	private String buyer;
	private Float initbid;
	private Float qty;
	private Float dealprice;
	private Float amount;
	private Date bidtime;
	private Date dealtime;
	private String status;

	public Trade() {
	}

	public Trade(String seller, String buyer, Float initbid, Float qty,
			Float dealprice, Float amount, Date bidtime, Date dealtime,
			String status) {
		this.seller = seller;
		this.buyer = buyer;
		this.initbid = initbid;
		this.qty = qty;
		this.dealprice = dealprice;
		this.amount = amount;
		this.bidtime = bidtime;
		this.dealtime = dealtime;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "tradeid", unique = true, nullable = false)
	public Integer getTradeid() {
		return this.tradeid;
	}

	public void setTradeid(Integer tradeid) {
		this.tradeid = tradeid;
	}

	@Column(name = "seller", length = 50)
	public String getSeller() {
		return this.seller;
	}

	public void setSeller(String seller) {
		this.seller = seller;
	}

	@Column(name = "buyer", length = 50)
	public String getBuyer() {
		return this.buyer;
	}

	public void setBuyer(String buyer) {
		this.buyer = buyer;
	}

	@Column(name = "initbid", precision = 12, scale = 0)
	public Float getInitbid() {
		return this.initbid;
	}

	public void setInitbid(Float initbid) {
		this.initbid = initbid;
	}

	@Column(name = "qty", precision = 12, scale = 0)
	public Float getQty() {
		return this.qty;
	}

	public void setQty(Float qty) {
		this.qty = qty;
	}

	@Column(name = "dealprice", precision = 12, scale = 0)
	public Float getDealprice() {
		return this.dealprice;
	}

	public void setDealprice(Float dealprice) {
		this.dealprice = dealprice;
	}

	@Column(name = "amount", precision = 12, scale = 0)
	public Float getAmount() {
		return this.amount;
	}

	public void setAmount(Float amount) {
		this.amount = amount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "bidtime", length = 19)
	public Date getBidtime() {
		return this.bidtime;
	}

	public void setBidtime(Date bidtime) {
		this.bidtime = bidtime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dealtime", length = 19)
	public Date getDealtime() {
		return this.dealtime;
	}

	public void setDealtime(Date dealtime) {
		this.dealtime = dealtime;
	}

	@Column(name = "status", length = 10)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
