package com.btc.trade.entity;

// Generated 2013-4-2 23:48:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "test")
public class User implements java.io.Serializable {

	private String userid;
	private String name;
	private Character sex;
	private Integer age;
	private String phone;
	private Float moneybalance;
	private Float btcbalance;
	private String note;

	public User() {
	}

	public User(String userid) {
		this.userid = userid;
	}

	public User(String userid, String name, Character sex, Integer age,
			String phone, Float moneybalance, Float btcbalance, String note) {
		this.userid = userid;
		this.name = name;
		this.sex = sex;
		this.age = age;
		this.phone = phone;
		this.moneybalance = moneybalance;
		this.btcbalance = btcbalance;
		this.note = note;
	}

	@Id
	@Column(name = "userid", unique = true, nullable = false, length = 50)
	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	@Column(name = "name", length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "sex", length = 1)
	public Character getSex() {
		return this.sex;
	}

	public void setSex(Character sex) {
		this.sex = sex;
	}

	@Column(name = "age")
	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	@Column(name = "phone", length = 20)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "moneybalance", precision = 12, scale = 0)
	public Float getMoneybalance() {
		return this.moneybalance;
	}

	public void setMoneybalance(Float moneybalance) {
		this.moneybalance = moneybalance;
	}

	@Column(name = "btcbalance", precision = 12, scale = 0)
	public Float getBtcbalance() {
		return this.btcbalance;
	}

	public void setBtcbalance(Float btcbalance) {
		this.btcbalance = btcbalance;
	}

	@Column(name = "note", length = 200)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}
